/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package LatihanModul6Lanjutan;

/**
 *
 * @author user
 */
public class UjiKebolehan extends javax.swing.JFrame {

    /**
     * Creates new form UjiKebolehan
     */
    public UjiKebolehan() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Btngrp = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        Nama = new javax.swing.JTextField();
        Tinggi = new javax.swing.JTextField();
        Berat = new javax.swing.JTextField();
        BBIdeal = new javax.swing.JTextField();
        Pr = new javax.swing.JRadioButton();
        Lk = new javax.swing.JRadioButton();
        Hitung = new javax.swing.JButton();
        Ulang = new javax.swing.JButton();
        Exit = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        Hasil = new javax.swing.JTextField();
        Saran = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setText("CEK IDEAL TUBUH");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(130, 10, 210, 30);

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel2.setText("Nama");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(50, 50, 50, 20);

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel3.setText("Tinggi Badan");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(50, 90, 90, 20);

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel4.setText("Berat Badan");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(50, 130, 80, 20);

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel5.setText("Jenis Kelamin");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(50, 170, 80, 20);

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel6.setText("cm");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(190, 100, 30, 30);

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel7.setText("kg");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(190, 140, 30, 30);

        Nama.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        Nama.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NamaActionPerformed(evt);
            }
        });
        getContentPane().add(Nama);
        Nama.setBounds(140, 50, 240, 30);

        Tinggi.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        Tinggi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TinggiActionPerformed(evt);
            }
        });
        getContentPane().add(Tinggi);
        Tinggi.setBounds(140, 90, 50, 30);

        Berat.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        Berat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BeratActionPerformed(evt);
            }
        });
        getContentPane().add(Berat);
        Berat.setBounds(140, 130, 50, 30);

        BBIdeal.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        BBIdeal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BBIdealActionPerformed(evt);
            }
        });
        getContentPane().add(BBIdeal);
        BBIdeal.setBounds(230, 260, 59, 30);

        Btngrp.add(Pr);
        Pr.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        Pr.setText("Perempuan");
        getContentPane().add(Pr);
        Pr.setBounds(140, 170, 110, 23);

        Btngrp.add(Lk);
        Lk.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        Lk.setText("Laki - Laki");
        Lk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LkActionPerformed(evt);
            }
        });
        getContentPane().add(Lk);
        Lk.setBounds(270, 170, 100, 23);

        Hitung.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        Hitung.setText("Hitung");
        Hitung.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                HitungActionPerformed(evt);
            }
        });
        getContentPane().add(Hitung);
        Hitung.setBounds(50, 210, 69, 30);

        Ulang.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        Ulang.setText("Ulangi");
        Ulang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UlangActionPerformed(evt);
            }
        });
        getContentPane().add(Ulang);
        Ulang.setBounds(180, 210, 65, 30);

        Exit.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        Exit.setText("Keluar");
        Exit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ExitActionPerformed(evt);
            }
        });
        getContentPane().add(Exit);
        Exit.setBounds(300, 210, 65, 30);

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel8.setText("Berat Badan Ideal Anda adalah ");
        getContentPane().add(jLabel8);
        jLabel8.setBounds(40, 260, 190, 40);

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel9.setText("kg");
        getContentPane().add(jLabel9);
        jLabel9.setBounds(290, 270, 40, 30);

        jLabel10.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel10.setText("Hasil Diagnosa");
        getContentPane().add(jLabel10);
        jLabel10.setBounds(160, 310, 100, 30);

        Hasil.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        Hasil.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                HasilActionPerformed(evt);
            }
        });
        getContentPane().add(Hasil);
        Hasil.setBounds(40, 340, 350, 30);

        Saran.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        getContentPane().add(Saran);
        Saran.setBounds(40, 390, 350, 30);

        setSize(new java.awt.Dimension(455, 506));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void NamaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NamaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_NamaActionPerformed

    private void TinggiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TinggiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TinggiActionPerformed

    private void BeratActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BeratActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BeratActionPerformed

    private void LkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LkActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_LkActionPerformed

    private void HasilActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_HasilActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_HasilActionPerformed

    private void ExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ExitActionPerformed
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_ExitActionPerformed

    private void UlangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UlangActionPerformed
        // TODO add your handling code here:
        Nama.setText(" ");
        Berat.setText(" ");
        Tinggi.setText(" ");
        Hasil.setText(" ");
        Saran.setText(" ");
        BBIdeal.setText(" ");
        Btngrp.clearSelection();
    }//GEN-LAST:event_UlangActionPerformed

    private void BBIdealActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BBIdealActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BBIdealActionPerformed

    private void HitungActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_HitungActionPerformed
        // TODO add your handling code here:
         double t, b, h =0;
        
        t = Double.valueOf(Tinggi.getText());
        b = Double.valueOf(Berat.getText());
        String nm = Nama.getText();
        
        if(Lk.isSelected()){
            h = (t-100);
        }else if(Pr.isSelected()){
            h = (t-104);
        }
        String temp = Double.toString(h);
        
        if (h>b){
            BBIdeal.setText(temp);
            Hasil.setText(" Maaf " + nm + ", Anda kekurangan berat badan ");
            Saran.setText("Dinner yuk");
        }else if(h<b){
            BBIdeal.setText(temp);
            Hasil.setText(" Maaf " + nm + ", Anda kelebihan berat badan ");
            Saran.setText("Diet yuk");
        }else{
            BBIdeal.setText(temp);
            Hasil.setText("Alhamdulillah" + nm+", Berat badan anda sudah ideal");
            Saran.setText("Ayo makan lagi biar genduut");
        } 
    }//GEN-LAST:event_HitungActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(UjiKebolehan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(UjiKebolehan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(UjiKebolehan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(UjiKebolehan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new UjiKebolehan().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField BBIdeal;
    private javax.swing.JTextField Berat;
    private javax.swing.ButtonGroup Btngrp;
    private javax.swing.JButton Exit;
    private javax.swing.JTextField Hasil;
    private javax.swing.JButton Hitung;
    private javax.swing.JRadioButton Lk;
    private javax.swing.JTextField Nama;
    private javax.swing.JRadioButton Pr;
    private javax.swing.JTextField Saran;
    private javax.swing.JTextField Tinggi;
    private javax.swing.JButton Ulang;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    // End of variables declaration//GEN-END:variables
}
